version: 2
updates:
  - package-ecosystem: "docker"
    directories:
      - "/agent"
      - "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directories:
      - "/agent"
      - "/server"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
