services:
  agent:
    image: tldevde/dockinv-agent:latest
    build:
      context: ./agent
      dockerfile: Dockerfile
    command: flask --app agent --debug run --host 0.0.0.0 --port 9999
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HTTP_TOKEN: your_secret
  server:
    image: tldevde/dockinv-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    command: flask --debug run --host 0.0.0.0 --port 8000
    restart: always
    ports:
     - "127.0.0.1:8000:8000"
    depends_on:
      - redis
    environment:
      - DATABASE_AUTO_UPGRADE=1
      - HOSTS_ADD_DEV_AGENT=1
    volumes:
        - ./data:/data
        - ./server:/app
  worker:
    image: tldevde/dockinv-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    command: celery -b redis://redis:6379/0 -A tasks worker -l info -B -s /tmp/celerybeat-schedule
    restart: always
    environment:
      - TASK_TRIVY_INTERVAL=1
      - TASK_XEOL_INTERVAL=1
      - TASK_DATA_COLLECTOR_INTERVAL=1
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
        - ./data:/data
        - ./server:/app
  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"
