services:
  agent:
    image: tldevde/dockinv-agent:latest
    build:
      context: ./agent
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HTTP_TOKEN: your_secret
  server:
    image: tldevde/dockinv-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
     - "127.0.0.1:8000:8000"
    depends_on:
      - redis
    volumes:
        - ./data:/data
        - ./server:/app
  worker:
    image: tldevde/dockinv-server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
    command: celery -A dockinv_server.tasks worker -l info -B
    restart: always
    environment:
      TASK_TRIVY_INTERVAL: 1
      TASK_XEOL_INTERVAL: 1
      TASK_DATA_COLLECTOR_INTERVAL: 1
    depends_on:
      - redis
    volumes:
        - ./data:/data
        - ./server:/app
  redis:
    image: redis:7-alpine
    ports:
      - "127.0.0.1:6379:6379"