services:
  agent:
    image: tldevde/dockinv-agent:latest
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      HTTP_TOKEN: your_secret

  server:
    image: tldevde/dockinv-server:latest
    restart: always
    ports:
     - "8000:8000"
    depends_on:
      - redis
    volumes:
        - data:/data

  worker:
    image: tldevde/dockinv-server:latest
    command: celery -A dockinv_server.tasks worker -l info -B
    restart: always
    depends_on:
      - redis
    volumes:
        - data:/data
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7-alpine
    restart: always


volumes:
  data: