import os


class Config:
    SQLALCHEMY_DATABASE_URI = os.getenv('SQLALCHEMY_DATABASE_URI', 'sqlite:////data/database.db')
    SQLALCHEMY_TRACK_MODIFICATIONS = False
    TASK_TRIVY_INTERVAL = os.getenv('TASK_TRIVY_INTERVAL', 60)
    TASK_XEOL_INTERVAL = os.getenv('TASK_XEOL_INTERVAL', 60)
    TASK_DATA_COLLECTOR_INTERVAL = os.getenv('TASK_DATA_COLLECTOR_INTERVAL', 15)
