name: Build and Push Docker Image

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to the Container registry
      uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image agent
      uses: docker/build-push-action@v4
      with:
        context: agent/
        push: true
        tags: |
          tldevde/dockinv-agent:latest
          tldevde/dockinv-agent:${{ github.event.release.tag_name }}
          ghcr.io/${{ github.repository }}/dockinv-agent:latest
          ghcr.io/${{ github.repository }}/dockinv-agent:${{ github.event.release.tag_name }}

    - name: Build and push Docker image server
      uses: docker/build-push-action@v4
      with:
        context: server/
        push: true
        tags: |
          tldevde/dockinv-server:latest
          tldevde/dockinv-server:${{ github.event.release.tag_name }}
          ghcr.io/${{ github.repository }}/dockinv-server:latest
          ghcr.io/${{ github.repository }}/dockinv-server:${{ github.event.release.tag_name }}