name: Build and Push Docker Image

on:
  release:
    types: [created]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image agent on main branch
      if: github.event_name == 'push'
      uses: docker/build-push-action@v4
      with:
        context: agent/
        push: true
        tags: |
          tldevde/dockinv-agent:main
          ghcr.io/${{ github.repository }}/dockinv-agent:main

    - name: Build and push Docker image agent on release
      if: github.event_name == 'release'
      uses: docker/build-push-action@v4
      with:
        context: agent/
        push: true
        tags: |
          tldevde/dockinv-agent:latest
          tldevde/dockinv-agent:${{ github.event.release.tag_name }}
          ghcr.io/${{ github.repository }}/dockinv-agent:latest
          ghcr.io/${{ github.repository }}/dockinv-agent:${{ github.event.release.tag_name }}

    - name: Build and push Docker image server on main branch
      if: github.event_name == 'push'
      uses: docker/build-push-action@v4
      with:
        context: server/
        push: true
        tags: |
          tldevde/dockinv-server:main
          ghcr.io/${{ github.repository }}/dockinv-server:main

    - name: Build and push Docker image server on release
      if: github.event_name == 'release'
      uses: docker/build-push-action@v4
      with:
        context: server/
        push: true
        tags: |
          tldevde/dockinv-server:latest
          tldevde/dockinv-server:${{ github.event.release.tag_name }}
          ghcr.io/${{ github.repository }}/dockinv-server:latest
          ghcr.io/${{ github.repository }}/dockinv-server:${{ github.event.release.tag_name }}